
title: "Infinitifall.net"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://infinitifall.net" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:categories/:title:output_ext
css_js_version: 8.2 # change to bypass browser cache

sass:
  sass_dir: _sass


# comment out the two lines below
# and uncomment out the lines in latex.html
# to use JS instead of static latex generation
kramdown:
  math_engine: katex


plugins:
- jekyll-toc


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
